### ISSUE TITLE
Le calcul de l'âge de mort pourrait être plus clair.

### ISSUE THREAD

**Issue by mbaudin47** [brunoscherrer/retraites#17]
Les deux lignes suivantes :

https://github.com/brunoscherrer/retraites/blob/5a0696dd54d5aab71db8b79244a9e2d3426d9e48/retraites/SimulateurRetraites.py#L855

pourraient être améliorées.

Le code pourrait utiliser les noms suivants:

```
    annee_naissance_brute = a - simulateur.A[s][a]
    annee_naissance = int(annee_naissance_brute + 0.5)
    age_mort = 60.0 + simulateur.EV[s][annee_naissance]
```

De plus, int(round()) serait plus approprié que ajouter 0.5.

**Comment by josephmure** [comment]
> De plus, int(round()) serait plus approprié que ajouter 0.5.

Je ne crois pas car le 0.5 ne sert pas à faciliter l'arrondi mais à réduire les effets de bord.

En effet, les gens nés en janvier ne doivent pas être traités de la même manière que les gens nés en décembre, car ils ont presque un an de différence. Ajouter 0.5 permet de faire comme si tout le monde naissait en juin/juillet, ce qui représente une erreur plus petite que de faire comme si tout le monde naissait en janvier : l'écart entre le 30 juin et le 1er janvier / entre le 1er juillet et le 31 décembre est de 6 mois, ce qui est plus faible que l'écart entre le 1er janvier et le 31 décembre qui est d'un an.

**Comment by mbaudin47** [comment]
Ok je comprends. En fait, dans l'équation arrondi(aaaa + 1/2 – A), ce n'est pas l'arrondi de aaaa – A. L'équation considère l'année aaaa + 1/2 c'est à dire le milieu de l'année. 

Du coups je comprends mieux l'exemple :

"Par exemple, si l’on renseigne dans le simulateur un âge effectif moyen de départ à la retraite égal à 63,5 ans en 2030, on utilisera, pour calculer la durée de vie passée à la retraite à cette date, l’espérance de vie à 60 ans de la génération née en : 2030+1/2-63,5 = 1967."

Est-ce qu'on est d'accord pour dire que, si l'éspérance de vie était une fonction régulière (par exemple un interpolateur) au lieu d'une table, ce problème serait résolu ?

**Comment by josephmure** [comment]
> Est-ce qu'on est d'accord pour dire que, si l'espérance de vie était une fonction régulière (par exemple un interpolateur) au lieu d'une table, ce problème serait résolu ?

Je ne suis pas sûr qu'il serait résolu car on ne connaîtrait quand même pas le moment précis du départ à la retraite, dont devrait être déduit le moment précis de la naissance qui serait l'entrée de la fonction régulière "espérance de vie à 60 ans".
